
# SEO

title: An Eye 4 AI with Annielytix
description: A Women in Tech Featured Podcast and Blog Covering all things AI.

# social
social_link: twitter
social_username: laura_e_edell
github_repo: annielytics # the GitHub repo name for your project
github_username: annielytix


theme_color: black

# Theme
remote_theme: 'internet-de-france/swiss'
baseurl: '/annielytics'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


